"use client";

import { useEffect, useState } from "react";
import {
  ArrowRight,
  Building2,
  CirclePlay,
  Home,
  Menu,
  MapPin,
  Menu as MenuIcon,
  Phone,
  Quote,
  ShieldCheck,
  Sparkles,
  X,
} from "lucide-react";
import { supabase } from "@/lib/supabase";

const defaultProjects = [
  { title: "Nexus Parkview", place: "Gulshan, Dhaka", kind: "Residential", status: "Ongoing", size: "1,850–2,450 sft", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85", text: "A calm, contemporary family residence shaped around light, space, and everyday ease." },
  { title: "Landmark One", place: "Banani, Dhaka", kind: "Commercial", status: "Upcoming", size: "1,200–8,000 sft", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85", text: "A confident commercial address for ambitious businesses, retail, and lifestyle brands." },
  { title: "The Grove Residences", place: "Uttara, Dhaka", kind: "Residential", status: "Completed", size: "1,450–1,900 sft", image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85", text: "Thoughtful apartments with green views, practical planning, and a warm sense of home." },
];

const defaultGallery = [
  ["Exterior", "Architectural expression", "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85"],
  ["Interior", "Living, refined", "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85"],
  ["Progress", "Built with care", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=85"],
];

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [filter, setFilter] = useState("All projects");
  const [projects, setProjects] = useState(defaultProjects);
  const [gallery, setGallery] = useState(defaultGallery);
  useEffect(() => { if (!supabase) return; Promise.all([supabase.from("properties").select("title,location,description,property_type,status,size,image_url").order("created_at", { ascending: false }), supabase.from("gallery_items").select("label,title,image_url").order("sort_order")]).then(([projectResult, galleryResult]) => { if (projectResult.data?.length) setProjects(projectResult.data.map((p) => ({ title: p.title, place: p.location, kind: p.property_type, status: p.status, size: p.size || "To be announced", image: p.image_url || defaultProjects[0].image, text: p.description || "A thoughtfully planned Nexus Landmark address." }))); if (galleryResult.data?.length) setGallery(galleryResult.data.map((g) => [g.label, g.title, g.image_url])); }); }, []);
  const visibleProjects = filter === "All projects" ? projects : projects.filter((project) => project.status === filter);

  const go = (id: string) => {
    setMenuOpen(false);
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <main className="min-h-screen bg-[#f8f9fb] text-[#0c2d49]">
      <div className="bg-[#092945] px-6 py-2 text-center text-[11px] font-medium tracking-[.12em] text-white/75">NEXUS LANDMARK — CREATING ADDRESSES WITH PURPOSE</div>
      <header className="sticky top-0 z-50 border-b border-[#0c2d49]/10 bg-white/95 shadow-[0_10px_35px_rgba(8,36,61,.08)] backdrop-blur-xl">
        <div className="mx-auto flex min-h-[76px] max-w-7xl items-center justify-between gap-5 px-6 lg:px-10">
          <button onClick={() => go("top")} className="flex items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#092945] text-[#c99554] shadow-lg"><Building2 size={22} /></span><span><span className="block font-serif text-[19px] font-semibold leading-none">Nexus <span className="text-[#bc8140]">Landmark</span></span><span className="mt-1 block text-[9px] font-bold uppercase tracking-[.22em] text-[#557084]">Properties & Development</span></span></button>
          <nav className="hidden items-center gap-7 text-[13px] font-semibold text-[#314b5e] lg:flex"><button onClick={() => go("about")}>About</button><button onClick={() => go("projects")}>Projects</button><button onClick={() => go("gallery")}>Gallery</button><button onClick={() => go("stories")}>Stories</button><button onClick={() => go("contact")}>Contact</button></nav>
          <div className="hidden items-center gap-4 lg:flex"><a href="tel:+8801611748100" className="flex items-center gap-2 text-xs font-semibold text-[#314b5e]"><Phone size={14} className="text-[#bc8140]" /> +880 1611 741 100</a><button onClick={() => go("contact")} className="rounded-md bg-[#bc8140] px-5 py-3 text-xs font-bold text-white transition hover:bg-[#092945]">Book a visit <ArrowRight size={14} className="ml-1 inline" /></button></div>
          <button className="lg:hidden" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
          {menuOpen && <div className="absolute left-0 right-0 top-[76px] border-t bg-white p-6 shadow-xl lg:hidden"><div className="flex flex-col gap-5 text-sm font-semibold"><button onClick={() => go("about")}>About</button><button onClick={() => go("projects")}>Projects</button><button onClick={() => go("gallery")}>Gallery</button><button onClick={() => go("stories")}>Stories</button><button onClick={() => go("contact")}>Contact</button></div></div>}
        </div>
      </header>

      <section id="top" className="relative overflow-hidden bg-[#092945]">
        <div className="mx-auto grid min-h-[650px] max-w-7xl items-center gap-10 px-6 py-16 lg:grid-cols-[.92fr_1.08fr] lg:px-10 lg:py-24"><div className="relative z-10"><p className="mb-6 flex items-center gap-2 text-xs font-bold uppercase tracking-[.25em] text-[#d7a263]"><Sparkles size={15} /> Better thinking. Better addresses.</p><h1 className="font-serif text-5xl leading-[1.08] tracking-tight text-white sm:text-7xl">Spaces that<br /><span className="italic text-[#d7a263]">move you forward.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-white/70">We create future-ready homes and commercial spaces in the places that matter—designed for the life you have now and the one you are building next.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => go("projects")} className="rounded-md bg-[#c99554] px-6 py-4 text-sm font-bold text-white transition hover:bg-white hover:text-[#092945]">Explore projects <ArrowRight size={16} className="ml-2 inline" /></button><button onClick={() => go("about")} className="rounded-md border border-white/25 px-6 py-4 text-sm font-bold text-white transition hover:bg-white hover:text-[#092945]">Why Nexus Landmark</button></div></div><div className="relative h-[450px] lg:h-[570px]"><div className="absolute inset-0 overflow-hidden rounded-lg"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=90" alt="Nexus Landmark signature residence" className="h-full w-full object-cover" /></div><div className="absolute -bottom-5 -left-4 flex w-60 items-center gap-4 rounded-lg bg-white p-4 shadow-2xl sm:left-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#f2e7d8] text-[#bc8140]"><ShieldCheck size={21} /></span><span><strong className="block font-serif text-2xl text-[#092945]">12+</strong><small className="text-[10px] font-bold uppercase tracking-wider text-[#557084]">Years of trusted work</small></span></div><div className="absolute right-4 top-5 rounded-lg border border-white/25 bg-[#092945]/75 px-4 py-3 text-xs text-white backdrop-blur"><span className="block text-[#d7a263]">Featured address</span><strong className="mt-1 block">Nexus Parkview · Gulshan</strong></div></div></div>
      </section>

      <section id="about" className="border-b border-[#0c2d49]/10 bg-white"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[.75fr_1.25fr] lg:px-10 lg:py-28"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-[#bc8140]">A more considered approach</p><h2 className="font-serif text-4xl leading-tight sm:text-5xl">A better address begins with <span className="italic text-[#bc8140]">better thinking.</span></h2></div><div className="grid gap-8 sm:grid-cols-2"><p className="text-[15px] leading-7 text-[#557084]">We bring planning, architecture, and customer care into one clear ownership journey. From site selection to handover, every decision is made to create calm, lasting value.</p><div className="grid grid-cols-2 gap-5"><div className="border-l-2 border-[#c99554] pl-4"><strong className="font-serif text-3xl">12+</strong><span className="mt-1 block text-xs text-[#557084]">Premium floors delivered</span></div><div className="border-l-2 border-[#c99554] pl-4"><strong className="font-serif text-3xl">100%</strong><span className="mt-1 block text-xs text-[#557084]">Accountable service</span></div></div></div></div></section>

      <section id="projects" className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-[#bc8140]">Our portfolio</p><h2 className="font-serif text-4xl sm:text-5xl">Addresses with intention.</h2></div><button onClick={() => go("contact")} className="self-start text-sm font-bold text-[#bc8140] sm:self-auto">Start a conversation <ArrowRight size={15} className="ml-1 inline" /></button></div><div className="mt-10 flex flex-wrap gap-2 border-b border-[#0c2d49]/10 pb-4">{["All projects", "Ongoing", "Upcoming", "Completed"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${filter === item ? "bg-[#092945] text-white" : "text-[#557084] hover:bg-[#eaf0f4]"}`}>{item}</button>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-3">{visibleProjects.map((project) => <article key={project.title} className="group overflow-hidden rounded-lg border border-[#0c2d49]/10 bg-white shadow-[0_10px_30px_rgba(8,36,61,.05)]"><div className="relative h-64 overflow-hidden"><img src={project.image} alt={project.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-[#092945]">{project.status}</span><span className="absolute bottom-4 left-4 rounded bg-[#092945]/85 px-3 py-1.5 text-[10px] font-semibold text-white backdrop-blur">{project.kind}</span></div><div className="p-6"><p className="flex items-center gap-1 text-xs font-semibold text-[#bc8140]"><MapPin size={13} /> {project.place}</p><h3 className="mt-3 font-serif text-2xl">{project.title}</h3><p className="mt-3 text-sm leading-6 text-[#557084]">{project.text}</p><div className="mt-6 flex items-center justify-between border-t border-[#0c2d49]/10 pt-4"><span className="text-xs font-semibold text-[#557084]">{project.size}</span><button onClick={() => go("contact")} className="text-xs font-bold text-[#bc8140]">View details <ArrowRight size={14} className="ml-1 inline" /></button></div></div></article>)}</div></section>

      <section id="gallery" className="bg-[#edf2f5] px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-[#bc8140]">See the detail</p><h2 className="font-serif text-4xl sm:text-5xl">A visual language of care.</h2></div><button className="hidden items-center gap-2 text-sm font-bold text-[#bc8140] sm:flex">Open gallery <ArrowRight size={15} /></button></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{gallery.map(([label, title, image]) => <div key={label} className="group relative h-72 overflow-hidden rounded-lg"><img src={image} alt={title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#092945]/80 via-transparent to-transparent" /><div className="absolute bottom-5 left-5 text-white"><span className="text-[10px] font-bold uppercase tracking-widest text-[#d7a263]">{label}</span><h3 className="mt-1 font-serif text-xl">{title}</h3></div></div>)}</div></div></section>

      <section id="stories" className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-[#bc8140]">The Nexus journal</p><h2 className="font-serif text-4xl leading-tight sm:text-5xl">Stories behind<br />the <span className="italic text-[#bc8140]">spaces.</span></h2><p className="mt-6 max-w-sm text-sm leading-6 text-[#557084]">Walk through our projects, meet the people behind them, and see how considered decisions become lasting places.</p><button onClick={() => go("contact")} className="mt-8 rounded-md border border-[#0c2d49]/20 px-5 py-3 text-xs font-bold">Watch project stories <CirclePlay size={15} className="ml-2 inline text-[#bc8140]" /></button></div><div className="grid gap-5 sm:grid-cols-2"><div className="relative min-h-64 overflow-hidden rounded-lg bg-[#092945] p-7 text-white"><MenuIcon className="absolute right-6 top-6 text-[#d7a263]" /><p className="text-xs uppercase tracking-widest text-[#d7a263]">01 / Perspective</p><h3 className="mt-20 font-serif text-2xl">Designing for the way Dhaka lives.</h3><p className="mt-3 text-xs leading-5 text-white/60">How local context shapes every Nexus Landmark address.</p></div><div className="relative min-h-64 overflow-hidden rounded-lg"><img src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85" alt="A Nexus Landmark interior" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[#092945]/50" /><div className="relative flex h-full flex-col justify-end p-7 text-white"><CirclePlay size={34} className="mb-auto text-[#d7a263]" /><p className="text-xs uppercase tracking-widest text-[#d7a263]">02 / Walkthrough</p><h3 className="mt-2 font-serif text-2xl">Inside Nexus Parkview.</h3></div></div></div></div></section>

      <section className="bg-[#092945] px-6 py-20 text-white lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><Quote className="mb-5 text-[#d7a263]" size={34} /><p className="font-serif text-3xl leading-tight sm:text-4xl">“The process felt clear from day one. The design is premium, but more importantly, it works beautifully for our family.”</p><p className="mt-7 text-xs font-bold uppercase tracking-widest text-[#d7a263]">— Farzana Chowdhury, Nexus homeowner</p></div><div className="grid gap-5 sm:grid-cols-3"><div className="border-l border-white/20 p-5"><Home size={20} className="mb-8 text-[#d7a263]" /><strong className="font-serif text-2xl">Clarity</strong><p className="mt-2 text-xs leading-5 text-white/60">At every milestone</p></div><div className="border-l border-white/20 p-5"><ShieldCheck size={20} className="mb-8 text-[#d7a263]" /><strong className="font-serif text-2xl">Care</strong><p className="mt-2 text-xs leading-5 text-white/60">Long after handover</p></div><div className="border-l border-white/20 p-5"><Building2 size={20} className="mb-8 text-[#d7a263]" /><strong className="font-serif text-2xl">Value</strong><p className="mt-2 text-xs leading-5 text-white/60">Built to last</p></div></div></div></section>

      <section id="contact" className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="relative overflow-hidden rounded-lg bg-[#c99554] px-7 py-14 text-center text-white sm:px-12"><div className="absolute -right-10 -top-24 h-72 w-72 rounded-full border-[30px] border-white/10" /><p className="relative text-xs font-bold uppercase tracking-[.22em] text-white/75">Your next address starts here</p><h2 className="relative mx-auto mt-4 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Ready to choose a place that feels like yours?</h2><p className="relative mx-auto mt-5 max-w-lg text-sm leading-6 text-white/80">Request a consultation, project brochure, or a private site visit with our team.</p><div className="relative mt-8 flex flex-wrap justify-center gap-3"><a href="tel:+8801611748100" className="rounded-md bg-[#092945] px-6 py-4 text-sm font-bold">Call our team</a><a href="mailto:hello@nexuslandmark.com" className="rounded-md border border-white/40 px-6 py-4 text-sm font-bold">Send an inquiry</a></div></div></section>

      <footer className="border-t border-[#0c2d49]/10 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-12 lg:grid-cols-[1.4fr_1fr_1fr] lg:px-10"><div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded bg-[#092945] text-[#c99554]"><Building2 size={19} /></span><span className="font-serif text-xl font-semibold">Nexus <span className="text-[#bc8140]">Landmark</span></span></div><p className="mt-5 max-w-xs text-sm leading-6 text-[#557084]">Premium residential and commercial developments shaped by design intelligence, local insight, and long-term trust.</p></div><div><h4 className="text-xs font-bold uppercase tracking-widest">Explore</h4><div className="mt-5 grid gap-3 text-sm text-[#557084]"><button className="text-left" onClick={() => go("about")}>About us</button><button className="text-left" onClick={() => go("projects")}>Our projects</button><button className="text-left" onClick={() => go("gallery")}>Gallery</button></div></div><div><h4 className="text-xs font-bold uppercase tracking-widest">Contact</h4><div className="mt-5 grid gap-3 text-sm text-[#557084]"><span>Dhaka, Bangladesh</span><a href="tel:+8801611748100">+880 1611 741 100</a><a href="mailto:hello@nexuslandmark.com">hello@nexuslandmark.com</a></div></div></div><div className="border-t border-[#0c2d49]/10 px-6 py-5 text-center text-xs text-[#557084] lg:px-10">© 2026 Nexus Landmark. Designed for better living.</div></footer>
    </main>
  );
}
