"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { ArrowLeft, Check, ImagePlus, LogOut, Plus, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type Tab = "content" | "projects" | "gallery" | "testimonials" | "services";
type Content = Record<string, string>;
type Project = { id: string; title: string; location: string; description?: string; property_type: string; status: string; size?: string; price?: string; image_url?: string };
type GalleryItem = { id: string; label: string; title: string; image_url: string };
type Testimonial = { id: string; quote: string; customer_name: string; customer_role?: string };
type Service = { id: string; title: string; description: string; icon?: string };

const defaultContent: Content = { hero_eyebrow: "Better thinking. Better addresses.", hero_description: "We create future-ready homes and commercial spaces in the places that matter—designed for the life you have now and the one you are building next.", about_description: "We bring planning, architecture, and customer care into one clear ownership journey. From site selection to handover, every decision is made to create calm, lasting value.", phone: "+880 1611 741 100", email: "hello@nexuslandmark.com", address: "Dhaka, Bangladesh", contact_title: "Ready to choose a place that feels like yours?", contact_description: "Request a consultation, project brochure, or a private site visit with our team." };

export default function CmsPage() {
  const router = useRouter();
  const [tab, setTab] = useState<Tab>("content");
  const [content, setContent] = useState<Content>(defaultContent);
  const [projects, setProjects] = useState<Project[]>([]);
  const [gallery, setGallery] = useState<GalleryItem[]>([]);
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [message, setMessage] = useState("");
  const [projectForm, setProjectForm] = useState<Omit<Project, "id">>({ title: "", location: "", description: "", property_type: "Residential", status: "Upcoming", size: "", price: "", image_url: "" });
  const [galleryForm, setGalleryForm] = useState({ label: "Exterior", title: "", image_url: "" });
  const [testimonialForm, setTestimonialForm] = useState<Record<string, string>>({ quote: "", customer_name: "", customer_role: "" });
  const [serviceForm, setServiceForm] = useState<Record<string, string>>({ title: "", description: "", icon: "" });

  useEffect(() => {
    async function load() {
      if (!supabase) { router.replace("/admin/login"); return; }
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) { router.replace("/admin/login"); return; }
      const [c, p, g, t, s] = await Promise.all([
        supabase.from("site_content").select("content").eq("id", "homepage").maybeSingle(),
        supabase.from("properties").select("id,title,location,description,property_type,status,size,price,image_url").order("created_at", { ascending: false }),
        supabase.from("gallery_items").select("id,label,title,image_url").order("sort_order"),
        supabase.from("testimonials").select("id,quote,customer_name,customer_role").order("created_at", { ascending: false }),
        supabase.from("services").select("id,title,description,icon").order("sort_order"),
      ]);
      if (c.data?.content) setContent({ ...defaultContent, ...c.data.content });
      if (p.data) setProjects(p.data);
      if (g.data) setGallery(g.data);
      if (t.data) setTestimonials(t.data);
      if (s.data) setServices(s.data);
    }
    load();
  }, [router]);

  function notify(text: string) { setMessage(text); setTimeout(() => setMessage(""), 3000); }
  async function saveContent() { if (!supabase) return; await supabase.from("site_content").upsert({ id: "homepage", content, updated_at: new Date().toISOString() }); notify("Website information saved"); }
  async function uploadImage(event: ChangeEvent<HTMLInputElement>, onUrl: (url: string) => void) { const file = event.target.files?.[0]; if (!file || !supabase) return; const path = `${Date.now()}-${file.name.replace(/[^a-zA-Z0-9.-]/g, "-")}`; const { error } = await supabase.storage.from("site-assets").upload(path, file, { upsert: true }); if (error) { notify(error.message); return; } const { data } = supabase.storage.from("site-assets").getPublicUrl(path); onUrl(data.publicUrl); notify("Image uploaded"); }
  async function addProject() { if (!supabase || !projectForm.title || !projectForm.location) return; const { data } = await supabase.from("properties").insert(projectForm).select().single(); if (data) setProjects((items) => [data, ...items]); setProjectForm({ title: "", location: "", description: "", property_type: "Residential", status: "Upcoming", size: "", price: "", image_url: "" }); notify("Project added"); }
  async function deleteRow(table: string, id: string) { if (!supabase || !window.confirm("Delete this item?")) return; await supabase.from(table).delete().eq("id", id); if (table === "properties") setProjects((items) => items.filter((item) => item.id !== id)); if (table === "gallery_items") setGallery((items) => items.filter((item) => item.id !== id)); if (table === "testimonials") setTestimonials((items) => items.filter((item) => item.id !== id)); if (table === "services") setServices((items) => items.filter((item) => item.id !== id)); notify("Deleted"); }
  async function addGallery() { if (!supabase || !galleryForm.title || !galleryForm.image_url) return; const { data } = await supabase.from("gallery_items").insert(galleryForm).select().single(); if (data) setGallery((items) => [...items, data]); setGalleryForm({ label: "Exterior", title: "", image_url: "" }); notify("Gallery item added"); }
  async function addTestimonial() { if (!supabase || !testimonialForm.quote || !testimonialForm.customer_name) return; const { data } = await supabase.from("testimonials").insert(testimonialForm).select().single(); if (data) setTestimonials((items) => [data, ...items]); setTestimonialForm({ quote: "", customer_name: "", customer_role: "" }); notify("Testimonial added"); }
  async function addService() { if (!supabase || !serviceForm.title || !serviceForm.description) return; const { data } = await supabase.from("services").insert(serviceForm).select().single(); if (data) setServices((items) => [...items, data]); setServiceForm({ title: "", description: "", icon: "" }); notify("Service added"); }
  async function signOut() { if (supabase) await supabase.auth.signOut(); router.push("/admin/login"); }

  const tabs: [Tab, string][] = [["content", "Homepage & contact"], ["projects", "Projects"], ["gallery", "Gallery"], ["testimonials", "Testimonials"], ["services", "Services"]];
  return <main className="min-h-screen bg-[#f5f7f9] text-[#092945]"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-[#0c2d49]/10 bg-white px-6 py-4 lg:px-10"><Link href="/admin" className="flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16} className="text-[#bc8140]" /> Dashboard</Link><div className="flex items-center gap-4"><span className="hidden text-xs font-bold text-[#557084] sm:block">Nexus Landmark CMS</span><button onClick={signOut} className="text-[#557084]"><LogOut size={17} /></button></div></header><div className="mx-auto max-w-7xl px-6 py-8 lg:px-10"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#bc8140]">Full content management</p><h1 className="mt-2 font-serif text-4xl">Edit your website</h1><p className="mt-2 text-sm text-[#557084]">Every saved change can be reflected on the public Nexus Landmark website.</p></div>{message && <span className="rounded-md bg-[#e7f4ed] px-4 py-3 text-xs font-bold text-[#31714d]"><Check size={14} className="mr-1 inline" />{message}</span>}</div><div className="mb-6 flex gap-2 overflow-x-auto border-b border-[#0c2d49]/10 pb-3">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${tab === key ? "bg-[#092945] text-white" : "text-[#557084] hover:bg-white"}`}>{label}</button>)}</div>{tab === "content" && <ContentEditor content={content} setContent={setContent} save={saveContent} />}{tab === "projects" && <ProjectsEditor projects={projects} form={projectForm} setForm={setProjectForm} upload={(e) => uploadImage(e, (url) => setProjectForm({ ...projectForm, image_url: url }))} add={addProject} remove={(id) => deleteRow("properties", id)} />}{tab === "gallery" && <GalleryEditor items={gallery} form={galleryForm} setForm={setGalleryForm} upload={(e) => uploadImage(e, (url) => setGalleryForm({ ...galleryForm, image_url: url }))} add={addGallery} remove={(id) => deleteRow("gallery_items", id)} />}{tab === "testimonials" && <SimpleEditor title="Testimonials" fields={testimonialForm} setFields={setTestimonialForm} add={addTestimonial} items={testimonials} remove={(id) => deleteRow("testimonials", id)} />}{tab === "services" && <SimpleEditor title="Services" fields={serviceForm} setFields={setServiceForm} add={addService} items={services} remove={(id) => deleteRow("services", id)} />}</div></main>;
}

function Field({ label, value, onChange, area = false }: { label: string; value: string; onChange: (value: string) => void; area?: boolean }) { return <label className="grid gap-2 text-xs font-bold text-[#314b5e]">{label}{area ? <textarea rows={4} value={value} onChange={(e) => onChange(e.target.value)} className="rounded-md border border-[#0c2d49]/10 bg-white p-3 text-sm font-normal outline-none focus:border-[#c99554]" /> : <input value={value} onChange={(e) => onChange(e.target.value)} className="rounded-md border border-[#0c2d49]/10 bg-white p-3 text-sm font-normal outline-none focus:border-[#c99554]" />}</label>; }
function Panel({ children }: { children: React.ReactNode }) { return <div className="rounded-lg border border-[#0c2d49]/10 bg-white p-6">{children}</div>; }
function ContentEditor({ content, setContent, save }: { content: Content; setContent: (content: Content) => void; save: () => void }) { const update = (key: string, value: string) => setContent({ ...content, [key]: value }); return <Panel><h2 className="font-serif text-3xl">Homepage, contact & SEO</h2><div className="mt-7 grid gap-5 md:grid-cols-2">{Object.entries(content).map(([key, value]) => <Field key={key} label={key.replaceAll("_", " ")} value={value} onChange={(next) => update(key, next)} area={key.includes("description") || key.includes("title")} />)}</div><button onClick={save} className="mt-7 rounded-md bg-[#092945] px-5 py-3 text-sm font-bold text-white">Save all homepage information</button></Panel>; }
function ProjectsEditor({ projects, form, setForm, upload, add, remove }: { projects: Project[]; form: Omit<Project, "id">; setForm: (form: Omit<Project, "id">) => void; upload: (e: ChangeEvent<HTMLInputElement>) => void; add: () => void; remove: (id: string) => void }) { const update = (key: string, value: string) => setForm({ ...form, [key]: value }); return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Panel><h2 className="font-serif text-3xl">Add project</h2><div className="mt-6 grid gap-4">{(["title", "location", "description", "size", "price"] as const).map((key) => <Field key={key} label={key} value={form[key] || ""} onChange={(value) => update(key, value)} area={key === "description"} />)}<label className="grid gap-2 text-xs font-bold">Type<select value={form.property_type} onChange={(e) => update("property_type", e.target.value)} className="rounded border p-3 text-sm"><option>Residential</option><option>Commercial</option></select></label><label className="grid gap-2 text-xs font-bold">Status<select value={form.status} onChange={(e) => update("status", e.target.value)} className="rounded border p-3 text-sm"><option>Ongoing</option><option>Upcoming</option><option>Completed</option></select></label><Field label="Image URL" value={form.image_url || ""} onChange={(value) => update("image_url", value)} /><label className="flex items-center gap-2 rounded border border-dashed p-3 text-xs font-bold text-[#557084]"><Upload size={16} />Upload image<input type="file" accept="image/*" onChange={upload} className="hidden" /></label><button onClick={add} className="rounded-md bg-[#092945] px-5 py-3 text-sm font-bold text-white"><Plus size={15} className="mr-1 inline" />Add project</button></div></Panel><Panel><h2 className="font-serif text-3xl">Published projects</h2><div className="mt-6 grid gap-3">{projects.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 rounded-md bg-[#f5f7f9] p-4"><div><strong className="text-sm">{item.title}</strong><p className="mt-1 text-xs text-[#557084]">{item.location} · {item.status}</p></div><button onClick={() => remove(item.id)} className="text-red-500"><Trash2 size={16} /></button></div>)}</div></Panel></div>; }
function GalleryEditor({ items, form, setForm, upload, add, remove }: { items: GalleryItem[]; form: { label: string; title: string; image_url: string }; setForm: (form: { label: string; title: string; image_url: string }) => void; upload: (e: ChangeEvent<HTMLInputElement>) => void; add: () => void; remove: (id: string) => void }) { return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Panel><h2 className="font-serif text-3xl">Add gallery image</h2><div className="mt-6 grid gap-4"><Field label="Label" value={form.label} onChange={(value) => setForm({ ...form, label: value })} /><Field label="Title" value={form.title} onChange={(value) => setForm({ ...form, title: value })} /><Field label="Image URL" value={form.image_url} onChange={(value) => setForm({ ...form, image_url: value })} /><label className="flex items-center gap-2 rounded border border-dashed p-3 text-xs font-bold text-[#557084]"><ImagePlus size={16} />Upload image<input type="file" accept="image/*" onChange={upload} className="hidden" /></label><button onClick={add} className="rounded-md bg-[#092945] px-5 py-3 text-sm font-bold text-white">Add to gallery</button></div></Panel><Panel><h2 className="font-serif text-3xl">Gallery items</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{items.map((item) => <div key={item.id} className="relative overflow-hidden rounded-md bg-[#f5f7f9]"><img src={item.image_url} alt={item.title} className="h-32 w-full object-cover" /><div className="flex items-center justify-between p-3"><span className="text-xs font-bold">{item.title}</span><button onClick={() => remove(item.id)} className="text-red-500"><Trash2 size={15} /></button></div></div>)}</div></Panel></div>; }
function SimpleEditor({ title, fields, setFields, add, items, remove }: { title: string; fields: Record<string, string>; setFields: (fields: Record<string, string>) => void; add: () => void; items: Array<{ id: string; [key: string]: string | undefined }>; remove: (id: string) => void }) { return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Panel><h2 className="font-serif text-3xl">Add {title.toLowerCase().slice(0, -1)}</h2><div className="mt-6 grid gap-4">{Object.entries(fields).map(([key, value]) => <Field key={key} label={key.replaceAll("_", " ")} value={value} onChange={(next) => setFields({ ...fields, [key]: next })} area={key.includes("quote") || key.includes("description")} />)}<button onClick={add} className="rounded-md bg-[#092945] px-5 py-3 text-sm font-bold text-white">Add {title.toLowerCase().slice(0, -1)}</button></div></Panel><Panel><h2 className="font-serif text-3xl">Published {title.toLowerCase()}</h2><div className="mt-6 grid gap-3">{items.map((item) => <div key={item.id} className="flex items-start justify-between gap-4 rounded-md bg-[#f5f7f9] p-4"><div><strong className="text-sm">{item.title || item.customer_name}</strong><p className="mt-1 text-xs text-[#557084]">{item.description || item.quote}</p></div><button onClick={() => remove(item.id)} className="text-red-500"><Trash2 size={16} /></button></div>)}</div></Panel></div>; }
